---
- name: creating document root
  file:
    path: /var/www/{{ _domain }}/public_html
    owner: www-data
    group: www-data
    mode: 0755
    state: directory
  register: document_root

- name: adding test index page
  lineinfile:
    create: yes
    insertafter: EOF
    owner: www-data
    group: www-data
    mode: 0644
    path: "{{ document_root.path }}/index.html"
    line: |
      <!DOCTYPE html>
      <html>
      <head>
      <style>
      body {background-color: #32363B;}
      h1   {color: #00B050;}
      </style>
      </head>
      <body>
      <h1>LAMP Stack: Powered by Linode Marketplace</h1>
      </body>
      </html>

- name: moving vhost template
  template:
    src: templates/vhost.conf.j2
    dest: "/etc/apache2/sites-available/{{ _domain }}.conf"
    owner: root
    group: root
    mode: 0644

- name: symlinking our vhost
  file:
    src: "/etc/apache2/sites-available/{{ _domain }}.conf"
    dest: "/etc/apache2/sites-enabled/{{ _domain }}.conf"
    owner: root
    group: root
    mode: 0644
    state: link
  notify: reload apache2
