---
 # apache
- name: installing apache
  apt:
    pkg:
    - apache2
    state: present

- name: enabling apache on boot
  service:
    name: apache2
    enabled: yes

- name: enable apache rewrite module
  apache2_module:
    name: rewrite
    state: present
  notify: reload apache2

- name: disable apache default site
  file:
    path: /etc/apache2/sites-enabled/000-default.conf
    state: absent

- name: apache configs for customer domain
  import_tasks: apache_configs.yml

# mysql
- name: installing mariadb
  apt:
    pkg:
    - mariadb-server
    - python3-mysqldb
    state: present
  register: mariadb

- name: running mysql secure installation
  import_role:
    name: securemysql

# php
- name: install php
  apt:
    pkg:
    - php-common
    - libapache2-mod-php
    - php-mysql
    state: present