---
# set_hostname
- name: setting up hostname
  import_role:
    name: hostname

# write _domain to vars.
- name: write _domain to vars
  lineinfile: 
    insertafter: EOF
    path: group_vars/linode/vars
    line: | 
      _domain: {{ _domain }}

# set customer supplied sudo user, password and SSH keys
- name: set sudo user
  import_role:
    name: sudouser
  when: username is defined

# dns creation
- name: create dns A record
  import_role:
    name: create_dns_record
  when: 
    - token_password is defined
    - default_dns is not defined

# sets customer supplied ssh pubkey to limited user
- name: set ssh pubkey
  import_role:
      name: sshkey
  when: 
    - pubkey is defined
    - username is defined

# apt_setup_update
- name: update system packages
  import_role:
    name: update_pkgs

# ufw_install
- name: enabling ufw
  import_role:
    name: ufw

# ufw rules 
- name: apply ufw rules
  import_tasks: ufw_rules.yml

# fail2ban
- name: enabling fail2ban
  import_role:
    name: fail2ban_install

 # apache
- name: installing apache
  apt:
    pkg:
    - apache2
    state: present

- name: enabling apache on boot
  service:
    name: apache2
    enabled: yes

- name: enable apache rewrite module
  apache2_module:
    name: rewrite
    state: present
  notify: reload apache2

- name: disable apache default site
  file:
    path: /etc/apache2/sites-enabled/000-default.conf
    state: absent

- name: apache configs for customer domain
  import_tasks: apache_configs.yml

# mysql
- name: installing mariadb
  apt:
    pkg:
    - mariadb-server
    - python3-mysqldb
    state: present
  register: mariadb

- name: running mysql secure installation
  import_role:
    name: securemysql

# php
- name: install php
  apt:
    pkg:
    - php-common
    - libapache2-mod-php
    - php-mysql
    state: present