---
 # nginx
- name: installing nginx
  apt:
    pkg:
    - nginx
    - nginx-common
    state: present

- name: enabling nginx on boot
  service:
    name: nginx
    enabled: yes

# php
- name: install PHP
  apt:
    pkg:
    - php-common
    - php-fpm
    - php-mysql
    state: present

- name: getting php version
  shell:
    cmd: "php -r \"echo PHP_MAJOR_VERSION.'.'.PHP_MINOR_VERSION;\""
  register: php_version

- name: starting php-fpm
  service:
    name: "php{{ php_version.stdout }}-fpm"
    state: started
    enabled: yes

- name: disable nginx default site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: nginx configs
  import_tasks: nginx_configs.yml

# mysql
- name: installing mariadb
  apt:
    pkg:
    - mariadb-server
    - python3-mysqldb
    state: present
  register: mariadb

- name: running mysql secure installation
  import_role:
    name: securemysql

