# linode ansible playbook

- name: configuring Wordpress
  hosts: localhost
  connection: local
  gather_facts: true
  any_errors_fatal: true
  user: root
  vars_files:
    - group_vars/linode/vars
  roles:
    - common
    # provioner will update with desired stack
    - PROVISIONER-WEBSERVER-STACK
    - wordpress
    - post