---
- name: installing fail2ban
  apt:
    pkg:
    - fail2ban

- name: activating ssh jail
  copy:
    src: /etc/fail2ban/fail2ban.conf
    dest: /etc/fail2ban/fail2ban.local
    owner: root
    group: root
    mode: 0644

- name: enabling fail2ban service
  service:
    name: fail2ban
    state: started